---
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: cnpg-nhost
spec:
  images:
    - image: harbor.hahomelabs.com/mycritters/cnpg-postgres:17
      major: 17

---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: example-db
  namespace: default
spec:
  imageCatalogRef:
    name: cnpg-nhost
    major: 17
    kind: ClusterImageCatalog
    apiGroup: postgresql.cnpg.io

  instances: 3

  postgresql:
    pg_hba:
      - hostnossl all all all md5
    shared_preload_libraries:
      - pg_stat_statements
      - timescaledb
      - pg_cron

  bootstrap:
    initdb:
      database: myapp
      owner: myapp
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS postgis;
        - CREATE EXTENSION IF NOT EXISTS vector;
        - CREATE EXTENSION IF NOT EXISTS pg_cron;

  storage:
    size: 10Gi
    storageClass: ceph-block
    resizeInUseVolumes: true

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nodeclass
            operator: In
            values:
            - general

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule

  monitoring:
    enablePodMonitor: true
